services:
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - 6379:6379

  web:
    build: ./
    container_name: web
    restart: always
    environment:
      - TERM=xterm
      - DJANGO_SETTINGS_MODULE=mst_chat.settings
    volumes:
      - ./:/app/
      # - static_volume:/app/staticfiles/
      - ./staticfiles:/staticfiles
    command: "daphne -b 0.0.0.0 -p 5000 mst_chat.asgi:application"  
    ports:
      - 80:5000
    # depends_on:
    #   - redis

# volumes:
#   static_volume:  